#!/usr/bin/env python

#
#	Author: historypeats <iam.historypeats@gmail.com>
#	Description: This tool can be used to audit your S3 Buckets
#	To find out what buckets and files have publicly exposed read permissions
#
#	Requirements: 
#		- boto
#		- blessings
#

from boto.s3.connection import S3Connection, S3ResponseError
from blessings import Terminal
from Queue import Queue
from threading import Thread
import sys
import argparse

#
#	DEFAULT VALUES
#
DEFAULT_THREADS = 10
DEFAULT_OUTFILE = '{0}.results'.format(sys.argv[0])


# 
#	Threading Classes
#
class WriteThread(Thread):
	''' This class handles threading for writing the results to a file '''

	def __init__(self, resultsQueue, filename):
		''' Constructor '''
		Thread.__init__(self)
		self.results = resultsQueue
		self.filename = filename


	def writeResult(self, result):
		with open(self.filename, 'a') as fd:
			fd.write('{0}\n'.format(result))


	def run(self):
		while True:
			self.result = self.results.get()
			self.writeResult(self.result)
			self.results.task_done()



class S3Thread(Thread):
	''' This class handles threading for retrieving S3 information '''

	def __init__(self, keyQueue, resultsQueue):
		''' Constructor '''
		Thread.__init__(self)
		self.keys = keyQueue
		self.results = resultsQueue


	def findPerms(self, key):
		''' Finds the permissions of a key and stores the result in a result queue '''
		
		try:
			t = Terminal()
			message = ''
			wmessage = ''

			for auth in key.get_acl().acl.grants:
				if auth.permission == 'READ':
					message = 'public: {0}'.format(str(key.name))
					wmessage = message

		except S3ResponseError:
			message = t.red +'error: Key does not exist: {0}'.format(str(key.name)) + t.normal
			wmessage = 'error: Key does not exist: {0}'.format(str(key.name))

		except:
			message = t.red + 'unknown: Uknown error in find_public() with key: {0}'.format(str(key.name)) + t.normal
			wmessage = 'unknown: Uknown error in find_public() with key: {0}'.format(str(key.name))

		finally:
			print message
			self.results.put(wmessage)


	def run(self):
		''' Thread Run '''
		while True:
			self.key = self.keys.get()
			self.findPerms(self.key)
			self.keys.task_done()


#
#	Functions
#
def getKeys(bucket):
	''' This returns a list of keys from a bucket '''

	try:
		t = Terminal()
		keys = list()
		
		print '[+] Getting keys for bucket {0}'.format(bucket)
		
		conn = S3Connection()
		bucket = conn.get_bucket(bucket)
		kObject = bucket.list()

		for key in kObject:
			keys.append(key)

		return keys
	except KeyboardInterrupt:
		sys.exit(t.red + '[!] ^C entered. Exiting.' + t.normal)

	except S3ResponseError:
		sys.exit(t.red + '[!] Bucket {0} either does not exist or you do not have permissions to access it.'.format(bucket) + t.normal)
	
	except:
		sys.exit(t.red + '[!] Unknown error in getKeys()' + t.normal)

	finally:
		conn.close()


def initArgs():
	''' Initialize Argparse '''

	parser = argparse.ArgumentParser(description='S3 Auditing Tool')
	parser.add_argument('bucket', help='The S3 bucket to audit.', type=str)
	parser.add_argument('-o', dest='outfile', help='The output file.', type=str, default=DEFAULT_OUTFILE)
	parser.add_argument('-t', dest='threads', help='How many threads to use.', type=int, default=DEFAULT_THREADS)

	return parser.parse_args()

#
#	Main
#
def main():
	''' Main '''

	# Parse args
	args = initArgs()	

	num_threads = args.threads
	
	# For storing S3 Keys
	keyQueue = Queue(maxsize=0)

	# For storing results and printing
	resultsQueue = Queue(maxsize=0)

	# Get list of keys from bucket
	keys = getKeys(args.bucket)

	# Put keys into Queue and get length
	for key in keys:
		keyQueue.put(key)
	
	# Remove this... for DEBUG 30 keys
	'''
	for i in xrange(30):
		keyQueue.put(keys[i])
	'''

	# Start S3 threads
	for t in xrange(num_threads):
		worker = S3Thread(keyQueue, resultsQueue)
		worker.setDaemon(True)
		worker.start()

	# Wait for threads to finish
	keyQueue.join()

	# Start Write Thread
	worker = WriteThread(resultsQueue, args.outfile)
	worker.setDaemon(True)
	worker.start()

	# Wait for threads to finish
	resultsQueue.join()

	print '[+] {0} keys found.'.format(str(len(keys)))


if __name__ == '__main__':
	main()
